export default {
    members: [
        // {
        //     name: 'Ruso',
        //     clues: ['Dormilón', 'A veces lloro', 'Me gusta comer'],
        //     nears: ['Manu',]
        // },
        // {
        //     name: 'Gringo',
        //     clues: ['Dormilón', 'A veces lloro', 'Me gusta comer'],
        //     nears: ['Manu',]
        // },
        {
            id: 1,
            name: 'Luthor',
            clues: ['A veces travieso', 'Soy Blanco', 'Hago reír'],
            nears: ['Christopher', 'Che Dario'],
            img_path: 'dog-2.svg',
        },
        {
            id: 2,
            name: 'Mau',
            clues: ['Paro durmiendo', 'A veces lloro', 'Soy color plomo'],
            nears: ['María', 'Elena'],
            img_path: 'cat-1.svg',
        },
        {
            id: 3,
            name: 'Tomy',
            clues: ['Pichilón', 'Bailarín', 'Soy juguetón'],
            nears: ['Diter', 'Olinda'],
            img_path: 'dog-happy.svg',
        },
        {
            id: 4,
            name: 'Luna',
            clues: ['Me gusta comer', 'Soy rastreador', 'Soy cazadora'],
            nears: ['Manu', 'Liz'],
            img_path: 'dog-1.svg',
        },
        {
            id: 5,
            name: 'Dixie',
            clues: [
                'Chambeo en el mercado',
                'Soy una mascota',
                'Orejas de avión',
            ],
            nears: ['Olinda', 'Manu'],
            img_path: 'dog-2.svg',
        },
        {
            id: 6,
            name: 'Liam',
            clues: ['Soy bailarín', 'Me gusta jugar', 'Veo dibujos en YouTube'],
            nears: ['Eudes', 'Jessica'],
            img_path: 'boy-1.svg',
        },
        {
            id: 7,
            name: 'Leandro',
            clues: [
                'Soy bien juguetón',
                'Tengo una tablet',
                'Sé contar en inglés',
            ],
            nears: ['Eudes', 'Jessica'],
            img_path: 'boy-2.svg',
        },
        {
            id: 8,
            name: 'Randy',
            clues: [
                'Soy Sporting Cristal 🤍',
                'Me gustan juegos de computadora',
                'Sigo a Youtubers de Dota',
            ],
            nears: ['Gladys', 'Elena'],
            img_path: 'teenager-1.svg',
        },
        {
            id: 9,
            name: 'Mamá Polita',
            clues: [
                'Siempre pienso en todos',
                'Soy bien fuerte',
                'No me gustan los flojos',
            ],
            nears: ['Lucha', 'Hilda', 'Walter', 'Gladys', 'Elena'],
            img_path: 'grandmother.svg',
        },
        {
            id: 10,
            name: 'Ángeles',
            clues: [
                'Me gusta leer libros',
                'Estudio enfermería',
                'Soy delgada',
            ],
            nears: ['Elena', 'Eudes'],
            img_path: 'girl-3.svg',
        },
        {
            id: 11,
            name: 'Leo',
            clues: [
                'Me gusta jugar fútbol',
                'Amigo grande',
                'River Plate 🤍',
            ],
            nears: ['Marlene', 'Diego'],
            img_path: 'teenager-1.svg',
        },
        {
            id: 12,
            name: 'Gladys',
            clues: ['Soy gritona', 'Perseverante', 'Canto muy fuerte'],
            nears: ['Mamá Polita', 'Randy'],
            img_path: 'mother.svg',
        },
        {
            id: 13,
            name: 'Alexia',
            clues: [
                'Me gusta hablar mucho',
                'Tomo muchas fotos',
                'Juego en mi celular',
            ],
            nears: ['Jeny', 'Paty'],
            img_path: 'girl-1.svg',
        },
        {
            id: 14,
            name: 'Christopher',
            clues: ['Me gusta jugar fútbol', 'Soy alto', 'Juego playstation'],
            nears: ['Dario', 'Paty'],
            img_path: 'teenager-2.svg',
        },
        {
            id: 15,
            name: 'Luchita',
            clues: ['Tengo una tienda', 'Soy bien alegre', 'Me gusta ir al mercado'],
            nears: ['Paty', 'Beto', 'Jenny'],
            img_path: 'mother-2.svg',
        },
        {
            id: 16,
            name: 'Hilda',
            clues: ['Soy bien fuerte', 'Vivo por el mercado', 'Tengo 4 hijos'],
            nears: ['Jannet', 'Jean Carlos'],
            img_path: 'mother.svg',
        },
        {
            id: 17,
            name: 'Paty',
            clues: ['Mi río fuerte', 'Me gusta hacer limpieza', 'Tengo varios dejos'],
            nears: ['Dario', 'Christopher'],
            img_path: 'woman-3.svg',
        },
        {
            id: 18,
            name: 'Beto',
            clues: ['Soy bailarín', 'Vendo carne', 'Soy super gracioso'],
            nears: ['Dayana', 'Lucha'],
            img_path: 'guy-5.svg',
        },
        {
            id: 19,
            name: 'Dayana',
            clues: ['Bailo Saya', 'Me gusta tomarme fotos', 'Uso lentes'],
            nears: ['Beto', 'Gloria'],
            img_path: 'girl-4.svg',
        },
        {
            id: 20,
            name: 'Walter',
            clues: ['Trabajo en el mercado', 'Soy bromista', 'Me gusta leer'],
            nears: ['Olinda', 'Manu'],
            img_path: 'father.svg',
        },
        {
            id: 21,
            name: 'Olinda',
            clues: ['Trabajo en el mercado', 'Soy dulcera', 'Me gusta cantar'],
            nears: ['Diter', 'Walter'],
            img_path: 'woman-1.svg',
        },
        {
            id: 22,
            name: 'Jenny',
            clues: ['Soy enfermera', 'Tengo una hija', 'Soy un poco alta'],
            nears: ['Alexia', 'Lucha'],
            img_path: 'girl-2.svg',
        },
        {
            id: 23,
            name: 'Yoel',
            clues: ['Soy ingeniero', 'Me gusta dormir', 'Soy delgado'],
            nears: ['Ángeles', 'Elena'],
            img_path: 'guy-2.svg',
        },
        {
            id: 24,
            name: 'Eudes',
            clues: ['Tengo 2 hijos', 'Me gusta jugar fútbol', 'Soy ingeniero'],
            nears: ['Elena', 'Jessica'],
            img_path: 'guy-3.svg',
        },
        {
            id: 25,
            name: 'Karen',
            clues: ['Me dicen Pochola', 'Vivo en Argentina', 'Soy de River Plate'],
            nears: ['Marlene', 'Leo', 'Barbie'],
            img_path: 'girl-4.svg',
        },
        {
            id: 26,
            name: 'Lizbeth',
            clues: ['Soy graciosa', 'Emprendedora', 'Me gusta Bailar'],
            nears: ['Walter', 'Diter', 'Manu'],
            img_path: 'girl-3.svg',
        },
    ],
}
